
name: Build Android App
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache Buildozer dependencies
      uses: actions/cache@v3
      with:
        path: .buildozer_cache
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          build-essential \
          libsqlite3-dev \
          sqlite3 \
          bzip2 \
          libbz2-dev \
          zlib1g-dev \
          libssl-dev \
          openssl \
          libgdbm-dev \
          libgdbm-compat-dev \
          liblzma-dev \
          libreadline-dev \
          libncursesw5-dev \
          libffi-dev \
          uuid-dev \
          libcurl4-openssl-dev

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        pip install Cython==0.29.33

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Android SDK
      run: |
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-*_latest.zip
        mkdir -p android-sdk/cmdline-tools
        mv cmdline-tools android-sdk/cmdline-tools/latest
        rm commandlinetools-linux-*_latest.zip
        export ANDROID_HOME=$GITHUB_WORKSPACE/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
        
    - name: Install Android SDK components
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" "ndk;25.2.9519653"
        sdkmanager "cmake;3.22.1"
        sdkmanager "extras;android;m2repository"
        sdkmanager "extras;google;m2repository"
        
    - name: Update Buildozer defaults
      run: |
        sed -i 's/android.ndk =.*/android.ndk = 25.2.9519653/g' buildozer.spec
        sed -i 's/android.sdk =.*/android.sdk = 33/g' buildozer.spec
        sed -i 's/android.build_tools =.*/android.build_tools = 33.0.0/g' buildozer.spec
        
    - name: Clean Buildozer cache
      run: |
        rm -rf ~/.buildozer/
        rm -rf .buildozer/
        
    - name: Build Android APK
      run: |
        buildozer android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: bin/*.apk

    - name: Create Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
