on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Install Android SDK command-line tools
      - name: Install Android SDK
        run: |
          # Install required packages
          sudo apt-get update
          sudo apt-get install -y wget unzip openjdk-11-jdk

          # Download Android command-line tools
          mkdir -p $HOME/.buildozer/android
          cd $HOME/.buildozer/android

          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip

          # Unzip and remove zip file
          unzip commandlinetools-linux-9477386_latest.zip
          rm commandlinetools-linux-9477386_latest.zip

          # Install SDK components and accept licenses
          yes | $HOME/.buildozer/android/cmdline-tools/bin/sdkmanager --licenses
          $HOME/.buildozer/android/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      # Build APK with Buildozer
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: buildozer -v android debug

      # Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ./bin/*.apk
