name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies for Buildozer
      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            python3-setuptools \
            python3-dev \
            build-essential \
            libssl-dev \
            libffi-dev \
            libsqlite3-dev \
            libjpeg-dev \
            liblcms2-dev \
            libfreetype6-dev \
            zlib1g-dev \
            libpng-dev \
            git \
            openjdk-8-jdk \
            android-sdk \
            android-tools-adb \
            android-tools-fastboot

      # Step 4: Install Buildozer
      - name: Install Buildozer
        run: |
          pip install buildozer

      # Step 5: Build APK with Buildozer
      - name: Build APK
        run: |
          buildozer android debug

      # Step 6: Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: kivy-apk
          path: ./bin/*.apk
