name: Build Kivy App
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          autoconf \
          libtool \
          pkg-config

    - name: Install Buildozer and Cython
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.5.0
        pip install cython==0.29.33

    - name: Set up Android SDK and NDK
      run: |
        sudo apt-get install -y wget unzip
        export ANDROID_HOME=$HOME/android-sdk
        export ANDROID_NDK_HOME=$HOME/android-ndk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        
        # Download and setup Android command line tools
        mkdir -p $ANDROID_HOME/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-8512546_latest.zip
        mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        rm commandlinetools-linux-8512546_latest.zip
        
        # Accept licenses and install required packages
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.0" \
          "ndk;23.1.7779620" \
          "cmake;3.22.1"
        
        # Set NDK path
        ln -s $ANDROID_HOME/ndk/23.1.7779620 $ANDROID_NDK_HOME
        
        # Verify AIDL installation
        test -f $ANDROID_HOME/build-tools/33.0.0/aidl || echo "AIDL not found"
        
        # Export paths for buildozer
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV

    - name: Create directory structure
      run: |
        mkdir -p data/images
        mkdir -p data/audio
        mkdir -p data/audiofx
        mkdir -p config

    - name: Verify icon.jpg exists
      run: |
        if [ ! -f "icon.jpg" ]; then
          echo "Warning: icon.jpg not found in root directory"
          exit 1
        fi

    - name: Clean Buildozer
      run: |
        buildozer android clean

    - name: Build with Buildozer
      env:
        BUILDOZER_WARN_ON_ROOT: 0
      run: |
        buildozer android debug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: bin/*.apk

    - name: Upload Build Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: |
          .buildozer/android/build/*/buildozer.log
          .buildozer/android/platform/*/build/build.log

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
